### ISSUE TITLE
Issue with transparent

### ISSUE THREAD

**Issue by dangtran47** [fcancelinha/nordern.nvim#5]
With `transaparent = true`
```lua 
-- my config in lazyvim
return {
  {
    "fcancelinha/nordern.nvim",
    priority = 1000,
    lazy = false,
    opts = {
      transparent = true,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nordern",
    },
  },
}

```
When focusing on a pane, other panes will be dimmed.

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/e519941c-72f1-4b61-8ea0-ffa65ccf7f95">

**Comment by fcancelinha** [comment]
Hey! I'm currently investigating the issue, I'll patch the colorscheme once it's resolved.

**Comment by fcancelinha** [comment]
@dangtran47 You can update to the latest version, the issued should be fixed, please let me know if there are other issues that you found that need fixing.
