### ISSUE TITLE
Visual Selection Highlighting Inconsistency

### ISSUE THREAD

**Issue by wnkz** [fcancelinha/nordern.nvim#6]
👋🏻 Hi,

First, thank you for the amazing colorscheme.

Now when using the nordern colorscheme, there's an inconsistency in the visual selection highlighting. Specifically, whitespace characters (such as spaces around the = sign) have a different background color compared to other selected text.

![image](https://github.com/user-attachments/assets/f749d41d-7362-4718-9539-6cdf6045623c)

From the screenshots in the README, I have a feeling that this isn't intentional.

Here's some info about my environment:
- macOS 14
- NVIM v0.10.1
- iTerm2 / kiTTY

Installed your theme with Lazy using this config
```lua
return {
    {
        "fcancelinha/nordern.nvim",
        branch = "master",
        priority = 1000,
    },
}
```

✌🏻

**Comment by fcancelinha** [comment]
Hello @wnkz thank you so much for the positive feedback ! I'm investigating the issue, do you have some option set to render whitespace ? 

something like this ? 
![image](https://github.com/user-attachments/assets/2352007c-5fef-4e62-b3ee-4f4c9a841523)

edit: I've added a soft color highlight for whitespace chars.

edit II: There's a new option to brighten conditionals, booleans and enums\readonly's named "brighten_conditionals" which will change the color of these tokens to aurora yellow from the new default frost sea color.

**Comment by wnkz** [comment]
Yes I have something like that 👇🏻
![image](https://github.com/user-attachments/assets/cc01a9ce-b348-4a9d-a174-725ff6cb0745)

The `brighten_conditionals` opt does not seem to make a difference but it "works" when I comment the config about my listchars 🤔 Other colorschemes I use do not seem to be affected by this

Here's my complete [config](https://github.com/wnkz/nvim-config/tree/nordern-colorscheme) with your theme if you need to have a look

**Comment by wnkz** [comment]
I've played around my `listchars` and don't remember why I put `space` in there ; it's way more readable when use something like this.

![image](https://github.com/user-attachments/assets/87e7901f-e4d8-404f-a7c6-94789b6a2fa1)

Nevertheless, I realized is that I just don't see my listchars when using your theme, here's an example with another colorscheme. I also noticed that you don't have the bright blue in the gutter on the cursorline like I have in the first screenshot.

![image](https://github.com/user-attachments/assets/a633c3d9-b037-4b65-b585-b6119b1243a8)

**Comment by fcancelinha** [comment]
I see, I'll keep investigating the issue. As for the gutter color, it's a bit too bright I agree, I'll modify it.

![image](https://github.com/user-attachments/assets/e08e7656-175e-426a-8864-3ef91e90731a)

Edit: I believe I have fixed the issue but could you confirm it on your end ? 
Regarding the gutter color, this is something I haven't managed to replicate on my system using your config options, to me it appears as the soft visual selection color, as seen in the screenshot above.

**Comment by wnkz** [comment]
I do see my listchars now and I don't know if it's related to your changes but I don't have the bright blue gutter background anymore!

![image](https://github.com/user-attachments/assets/06a79c54-87e6-4e4c-ac00-faaf6c6f1776)

As far as I'm concerned, this is resolved. Thanks again for your amazing work 🙌🏻
